export { default as Sidebar } from "../components/SideBar";
export { default as Loader } from "../components/Loader";
export { default as NavBar } from "../components/NavBar";
export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as TechStack } from "./TechStack";
export { default as Projects } from "./Projects";
export { default as Contact } from "../sections/Contact";
export { default as Footer } from "../components/Footer";
